<a href="https://colab.research.google.com/github/deepakyadav043/Python-Pandas_Library/blob/main/pandas_class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [ ]:
import pandas as pd
a = {
    "name": ["Devraj","Bob","nehu","kamlesh","Ramesh"],
    'Age' : [25,20,18,19,90],
    "Score":[80,90,70,77,88]
}
b = pd.DataFrame(a)
#1 .Select Single Column "Age"
b[b['Age']>23]

#2 Select single column "Score">85
b[b['Score']>85]

#Multiple Condition (AND) : Age >27 AND Score >85
b[(b['Age']>27) & b['Score']>85]

#3 Multiple Conditions (OR): Age >27 Or(|) Score >85
b[(b['Age']>27)| (b['Score']>85)]

#5 Not(~)
b[~(b['Score']>85)]

#6 Age>22 and Score>80

b['Age']>22 & (b['Score'] >85)

0    True
1    True
2    True
3    True
4    True
dtype: bool

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [ ]:
#1. Age >25 AND Score >85
b[(b['Age'] >25) & (b['Score']>85)]
#2. Age < 35 or Score >= 90
b[(b['Age']<35) | (b['Score']>= 90)]
#3. Age Between 25 and 35(inclusive)
#25,26,27,28,29,30,32,32,33,34,35
b[(b['Age'] >= 25)& (b['Age'] <= 35)]

     name  Age  Score
0  Devraj   25     80

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [ ]:
#1 .Simple Query: Age > 25
print(b.query("Age > 25"))

#2 Multiple conditions using Query : Age < 35 and Score >= 85
print(b.query("Age<35 and Score >= 85"))

# Multiple Conditions using query :Age >= 30 and Score >= 90
print(b.query("Age >= 30 and  Score >= 90"))

#4.  Threshhold(@)
Score = 90 #Variable
b.query("Score >= @Score")

     name  Age  Score
4  Ramesh   90     88
  name  Age  Score
1  Bob   20     90
Empty DataFrame
Columns: [name, Age, Score]
Index: []

  name  Age  Score
1  Bob   20     90

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [ ]:
print(b)
print(b.columns)
#1.Convert name to Lowercase().
print(b['name'].str.lower())

#2.Convert name to upparcase()
print(b['name'].str.upper())

#3 Title() --> Capitialize first letter of all the words.
print(b['name'].str.title())

#4 Replace a Substring ('oldString',NewString)
b['name'].str.replace('nehu', 'Nehu')


##5. check if Name column contsins the letter 'a'
b['name'].str.contains('a')

#6 .startswith('Letter') --> Letter starting with
b[b['name'].str.startswith('D')]

#7 .endswith("Letter") -->  Letter Ends with
b[b['name'].str.endswith('e')]

      name  Age  Score
0   Devraj   25     80
1      Bob   20     90
2     nehu   18     70
3  kamlesh   19     77
4   Ramesh   90     88
Index(['name', 'Age', 'Score'], dtype='object')
0     devraj
1        bob
2       nehu
3    kamlesh
4     ramesh
Name: name, dtype: object
0     DEVRAJ
1        BOB
2       NEHU
3    KAMLESH
4     RAMESH
Name: name, dtype: object
0     Devraj
1        Bob
2       Nehu
3    Kamlesh
4     Ramesh
Name: name, dtype: object

Empty DataFrame
Columns: [name, Age, Score]
Index: []

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.